apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi
  labels:
    app: fastapi
    project: piercuta
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        project: piercuta
        env: dev
        piercuta.com/node-type: fastapi
    spec:
      nodeSelector:
        piercuta.com/node-type: fastapi
      serviceAccountName: fastapi-sa
      containers:
      - name: fastapi
        image: "532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app:dev"
        env:
        - name: ENV_NAME
          value: "dev"
        - name: PROJECT_NAME
          value: "piercuta"
        - name: POSTGRES_SERVER
          value: "piercuta-dev-aurora-cluster.cluster-c36i2qm0y4yz.eu-west-1.rds.amazonaws.com"
        - name: POSTGRES_USER
          value: "postgres"
        - name: FRONTEND_HOST
          value: "https://my-frontend.piercuta.com"
        - name: AWS_REGION
          value: "eu-west-1"
        - name: AWS_SECRET_ARN
          value: "arn:aws:secretsmanager:eu-west-1:532673134317:secret:rds!cluster-bf1b0f60-73b1-43aa-ae9c-2350398361c1-8FSnWF"
        - name: POSTGRES_DB
          value: "app"
        - name: POSTGRES_PORT
          value: "5432"
        - name: SECRET_KEY
          value: "Osa3ZuhC7d6ssbF4XmKtYlemuTdbefkPvuZgOCRTrLg"
        - name: FIRST_SUPERUSER
          value: "admin@example.com"
        - name: FIRST_SUPERUSER_PASSWORD
          value: "Coucou123!"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 1Gi
            memory: 1Gi
          limits:
            cpu: 1Gi
            memory: 1Gi